name: Build and update dist

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.17.0]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run type-check
    - run: npm run build-prod
    - run: npm run tes
    - name: Update dist folder
      uses: test-room-7/action-update-file@v2
      with:
          file-path: |
              dist/*.js
              dist/*.map
              dist/*.txt
          commit-msg: Auto-update distribution
          github-token: ${{ secrets.GITHUB_TOKEN }}
